# Parameters used to generate this project with aem-project-archetype

groupId=com.searchstax.aem.connector
artifactId=searchstax-aem-connector
version=1.0.0-SNAPSHOT
package=com.searchstax.aem.connector
appId=searchstaxconnector
appTitle=SearchStax AEM Connector
aemVersion=cloud
sdkVersion=latest
archetypeVersion=56
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=none
singleCountry=y
includeDispatcherConfig=n
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
includeFormsheadless=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
